### ISSUE TITLE
Center the cart image

### ISSUE THREAD

**Issue by calmaemilia** [mirceah99/embow#9]

**Comment by calmaemilia** [comment]
![image](https://user-images.githubusercontent.com/126419513/223521022-5f4320d7-f26f-4fd7-92b5-af7634fd4777.jpeg)
![image](https://user-images.githubusercontent.com/126419513/223521053-ea490093-a430-4a9a-ac1c-050a18115773.jpeg)

Do you notice a difference? @mirceah99

**Comment by mirceah99** [comment]
Please check again, not sure if u saw the updated version.
I htink we should add also somewhere the site version, or idk.
If not let me know, give me other cart picture, where the cart is looking centered, because from the begining the picture was centered, but maybe it seems uncentered because is not simetrical

![Image](https://user-images.githubusercontent.com/81265688/223532351-88415ee2-849f-4cd6-9bf8-92799194dd23.png)

**Comment by mirceah99** [comment]
Good job

**Comment by mirceah99** [comment]
Done
